### ISSUE TITLE
Versions like `1.8_292` break automatic channel generation

### ISSUE THREAD

**Issue by jvmakine** [cashapp/hermit#103]
Manifest with a version `version "1.8_292"` failed the package validation with:
```
warn: invalid manifest reference openjdk8@1.8 in openjdk8.hcl: @1.8: no version found matching 1.8.*
```

**Comment by alecthomas** [comment]
This is by design. Version `1.8` is the exact version number so there's no sense making a channel `1.8`. Hermit makes channels for the "super" version, eg. for `1.8.2` it will make `@1.8`

**Comment by alecthomas** [comment]
Reopen if you think there's something different we should do here.
