### ISSUE TITLE
Move GitHub logic in the cache package into a custom HTTP transport

### ISSUE THREAD

**Issue by alecthomas** [cashapp/hermit#121]
Related to #120 - this and the API discovery of private release artefacts could be rolled into a custom HTTP transport. For precedent, [go-github](https://github.com/google/go-github) does this transparent auth internally.

**Comment by lox** [comment]
This is the round-tripper you'd use for GH App Installation tokens: https://github.com/bradleyfalzon/ghinstallation

**Comment by alecthomas** [comment]
Yeah this is already done.

**Comment by alecthomas** [comment]
Sorry, to be more specific - the logic described in this _issue_ is already implemented - the stuff in ghinstallation, we should look at for the private auto-version+GH release downloads.
