### ISSUE TITLE
Add `hermit install <pkg>-latest` feature

### ISSUE THREAD

**Issue by nschmeller** [cashapp/hermit#199]
Hey, just getting started with Hermit, but I noticed that I have to specify the version of the package I want to install using `hermit install`. 

To do this, I have to run `hermit search <pkg>` and choose a version that looks good to me. I usually want to install the latest version, but when I tried `hermit install <pkg>-latest`, I got an error that said "unknown package". 

I think this could be a great feature!

**Comment by alecthomas** [comment]
You're in luck, this feature already exists, but it uses a feature called channels. The syntax is `hermit install pkg@latest`.

**Comment by nschmeller** [comment]
Wow, thanks! Guess I missed it in the docs.

**Comment by alecthomas** [comment]
One difference is that the latest channel will always track the latest version, upgrading automatically. To just install the latest version and pin to it, use `hermit install pkg`.
