### ISSUE TITLE
[Question] How does Hermit compare to Docker?

### ISSUE THREAD

**Issue by RilDev** [cashapp/hermit#216]
Good day,

I recently found about Hermit from the console.dev news letter, and I was wondering in what way does Hermit differs from Docker?

Could you give me examples to show how the two would solve (differently) the problem of having a project working in isolation from the host system?

Thank you!

**Comment by alecthomas** [comment]
Welcome. This is [covered in the FAQ](https://cashapp.github.io/hermit/faq/#docker).

**Comment by alecthomas** [comment]
But I would say the main difference from a usability perspective is that users just add the `bin` directory to their `$PATH` and Hermit will self-install, the install the tool, then run it. So users don't need Docker or Hermit to be preinstalled in order to work.

**Comment by RilDev** [comment]
Thank you for the explanation.
