### ISSUE TITLE
Improved runtime deps via source package environment

### ISSUE THREAD

**Issue by jvmakine** [cashapp/hermit#227]
At the moment, when we have a Hermit environment in the source package, we inject the binaries of the packages in the source to the PATH. The binaries injected are from the bin stubs at `~/Library/Caches/hermit/binaries/`

- [ ] To properly encapsulate the runtime dependencies, we should instead inject the `<env>/bin` to the PATH fir the runtime dependency env, and call the dependencies via the hermit in the source environment. 
- [ ] We should also not install runtime dependencies from the source env, instead et hermit to fetch the runtime dependencies on call. This is so we can mix runtime and buildtime deps without additional cost
- [ ] We do not want to flatten the runtime deps for environment based packages anymore.
- [ ] We still want to keep `runtime-deps` at package manifests if we want to inject runtime dependencies to packages not packaged by us. For these, we should check that there are no conflicting binaries
- [ ] We should add a test to see that different versions of same package can be correctly called as runtime dependencies

**Comment by OmarTawfik** [comment]
@jvmakine this should be fixed by https://github.com/cashapp/hermit/pull/230
Please let me know if there is anything else we can do before closing this.

**Comment by jvmakine** [comment]
This has been implemented in https://github.com/cashapp/hermit/pull/230
