### ISSUE TITLE
Hermit fails when `$HOME` is not defined

### ISSUE THREAD

**Issue by nickbreaton** [cashapp/hermit#239]
While its generally considered good practice and [POSIX spec](https://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap08.html) complaint to ensure `$HOME` is set, it can be common in the Node.js world to spawn a child node process with a limited set of environment variables. 

This occurs with [the Architect project](https://github.com/architect/sandbox/blob/6c79a0f8ca06ac44d910e64c8307b68ffbe6505c/src/invoke-lambda/env/index.js#L17-L48) where they are trying to locally emulate an AWS Lambda environment. Running `node` does not require `$HOME` generally, but when Hermit is wrapping its binary, [it now does](https://github.com/cashapp/hermit/blob/502f8f8cac20aea9c338432e454c54c2da427f87/bin/hermit#L8). 

[Here is a minimal, reproducible example.](https://github.com/nickbreaton/hermit-home-issue-reproduction) ([zip](https://github.com/cashapp/hermit/files/8365716/hermit-home-issue-reproduction-main.zip))

I'd propose using the `~` inside of hermit as an alternative to the `$HOME` variable to account for this use-case.

**Comment by alecthomas** [comment]
Alas this alone did not fix the issue as Hermit itself relies on $HOME.
