### ISSUE TITLE
`hermit install` should warn but not fail without network if all packages are already installed

### ISSUE THREAD

**Issue by alecthomas** [cashapp/hermit#259]
Currently it just completely fails, making the IJ plugin unusable. There is no real reason for this to be the case if all of the packages are already installed.

See also #258 which if fixed would probably solve this issue somewhat.

```
Error while running ./hermit 
error:https://github.com/cashapp/hermit-packages.git: Cloning into '/Users/aat/Library/Caches/hermit/sources/6682e3c492bdd27fac0db80685cb1df7bd13fda32bb9765ca15e895df13eb3cc-2486539884'...
fatal: unable to access 'https://github.com/cashapp/hermit-packages.git/': Could not resolve host: github.com

fatal:hermit: git sync failed: git clone --depth=1 https://github.com/cashapp/hermit-packages.git /Users/aat/Library/Caches/hermit/sources/6682e3c492bdd27fac0db80685cb1df7bd13fda32bb9765ca15e895df13eb3cc-2486539884 failed: exit status 128
```

**Comment by nickajacks1** [comment]
I cannot seem to reproduce this. When all packages are installed, `hermit install` just exits immediately with exit code 0 whether I am connected to the network or not.

**Comment by alecthomas** [comment]
Excellent! It must have been fixed in the interim!
