### ISSUE TITLE
Add integrity checks for packages

### ISSUE THREAD

**Issue by agateau** [cashapp/hermit#263]
I love the idea of Hermit, but given that it downloads pre-compiled binary archives, it seems to me it can be vulnerable to supply-chain attacks: someone could replace an existing archive from a server and Hermit would download it without noticing the change. This could be mitigated by storing a sha256 checksum of each version in the package manifest.

**Comment by alecthomas** [comment]
Hermit does support [this](https://cashapp.github.io/hermit/packaging/schema/manifest/) (search for sha256).

**Comment by agateau** [comment]
Oh that's nice, but it doesn't look very widespread. Do you plan to make it mandatory?

**Comment by alecthomas** [comment]
We've talked about this a bit in the past, and the issue is that `sha256` can't coexist with auto-versioning. We would need to add support for a `sha256sums = {...}` map, but do not currently have the bandwidth.
