### ISSUE TITLE
On mac with zsh, you need gmake so that the "source" command works in your makefiles

### ISSUE THREAD

**Issue by gedw99** [cashapp/hermit#348]
on a mac with zsh you need gmake ( not make ) , so that **source** command works in your makefiles.

maybe worth adding this to https://cashapp.github.io/hermit/usage/get-started/#initialising-a-project

then the init works:

```
	# add to zsh so the hermit hooks can fire.
	hermit shell-hooks --zsh

	# create a local bin with the hermit stuff.
	hermit init

	# loads the env.
	source ./bin/activate-hermit
```

**Comment by alecthomas** [comment]
Can you describe how to reproduce the issue?

**Comment by gedw99** [comment]
hey

The repo is to use make versus gmake. 

 standard make that the MAC OS already has and the binary is called "make"

then install make via brew. This is the gnu make and the binary is called "gmake"

when you use gmake everything works.

when you ue standard mac, it fails.

---

How to fix it ?

Just tell everyone to use gmake, so we have the same make on Linux and Darwin.

Or 

Work to what script is failing. I don't have the code in front of me right now unfortunately.   Sorry - but might get time to try again in a few days...

**Comment by alecthomas** [comment]
gmake is available in hermit for this very reason: `hermit install make`

**Comment by gedw99** [comment]
Face palm :) 

thanks

**Comment by gedw99** [comment]
I made exactly the same problem with core utilities on a team mates dev system . 

also with core utils AND gmake, on a Mac, the trick is to remap the other to gnake, so the user just types make it just works . Not sure yet if I need to do that with hermit - probably not since it’s a jailed env

**Comment by alecthomas** [comment]
It won't be necessary if users activate the env. I typically also put an assertion in the Makefile checking for that it is being executed with the correct version of make.
