### ISSUE TITLE
How to install 3rd party manifests?

### ISSUE THREAD

**Issue by jmandel1027** [cashapp/hermit#353]
Hi there, 

I've had this problem a few times and it's come up for me again, I can't seem to find a way to install packages that I've created manifests for. I love using hermit but the docs seem to be incomplete on this subject. Is the example in [the tutorial](https://cashapp.github.io/hermit/packaging/tutorial/) made by adding these packages directly in `hermit-packages`?

I'm trying to explicitly understand where to put a user-created manifest and what command I need to run so I can install it in my hermit config on my project.

Thanks again for the help!

**Comment by alecthomas** [comment]
Glad you like it!

It is documented here: https://cashapp.github.io/hermit/usage/config/ . You can see an example here: https://github.com/cashapp/hermit-packages/blob/master/bin/hermit.hcl

There's also the [tutorial](https://cashapp.github.io/hermit/packaging/tutorial/#clone-and-activate-the-manifest-repository), which describes how to use the hermit-packages repository to test packages.

You can add this to any existing environment. You can also use `hermit status` to list existing sources.

I typically use something like this:

```hcl
sources = ["env:///bin/packages", "https://github.com/cashapp/hermit-packages.git"]
```

**Comment by jmandel1027** [comment]
Oooooohhhh gotcha, this makes sense, thanks for the quick reply!
