### ISSUE TITLE
Use "$HOME/.local/bin" for installing hermit's binary in Gnu+Linux

### ISSUE THREAD

**Issue by CIAvash** [cashapp/hermit#42]
That's what XDG spec recommends.

**Comment by alecthomas** [comment]
That seems reasonable. We've recently been discussing the user bin directory location, so we'll have a think about this. Do you know off-hand if, as the XDG spec suggests, `~/.local/bin` is included in the `$PATH` on many distros?

**Comment by CIAvash** [comment]
I don't know, but I don't think so. The Arch Linux wiki even uses `~/bin` as an example [here](https://wiki.archlinux.org/title/Environment_variables#Globally) 🤦‍♂️.

**Comment by alecthomas** [comment]
Yeah I have to say that I chose `~/bin` because it seems to be quite commonly added to the `PATH` by the OS, so while `~/.local/bin` might be more "correct" I'm not sure it's pragmatic.

**Comment by alecthomas** [comment]
I think while theoretically this is a good idea, most Linux distributions in the wild seem to prefer `~/bin`.
